[build]
command = "echo 'No build step needed'"
publish = "public"
functions = "src"

[dev]
command = "netlify dev"
port = 8888
publish = "public"

[[redirects]]
from = "/prev"
to = "/.netlify/functions/index"
status = 200
conditions = { Role = [] }

[[redirects]]
from = "/next"
to = "/.netlify/functions/index"
status = 200
conditions = { Role = [] }

[[redirects]]
from = "/random"
to = "/.netlify/functions/index"
status = 200
conditions = { Role = [] }

[[redirects]]
from = "/members.json"
to = "/.netlify/functions/index"
status = 200
conditions = { Role = [] }
